### ISSUE TITLE
design and implement vcf adapter

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-plugin-gdc#33]
controlled data on the gdc can be formatted in vcf and we need an adapter for it

**Comment by cmdcolin** [comment]
It might be useful to add this code in the main codebase. The main codebase currently only accepts "tabixed VCF" but could probably benefit from opening plain text VCF in some cases like this one

**Comment by carolinebridge-oicr** [comment]
solved by https://github.com/GMOD/jbrowse-components/pull/2068
