### ISSUE TITLE
Demo config file http 404

### ISSUE THREAD

**Issue by SamCT** [GMOD/jbrowse-plugin-gdc#72]
Hi JBrowse team,

Wanted to let you know that the config.json is not working properly for the demo.

https://s3.amazonaws.com/jbrowse.org/code/jb2/main/index.html?config=https%3A%2F%2Funpkg.com%2Fjbrowse-plugin-gdc%2Fdist%2Fconfig.json

Sam

**Comment by SamCT** [comment]
No problem. I just stumbled across it :)

**Comment by cmdcolin** [comment]
back in business :) thanks for reporting
